version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
  api:
    image: ghcr.io/k4czp3r/botplusplus
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - mongo
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME:
  #     ME_CONFIG_MONGODB_ADMINPASSWORD:
  #     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  #   depends_on:
  #     - mongo
